### PR TITLE
Makes Array field compatible with react native and fixes #64

### LINKED ISSUE #64: React native with Array field: 'There is no field "parentField.0.0.childField" in the schema'
I'm trying to set up the Array field with react native. If all goes well, I'll make a pull request. For right now, I'm stumped by this issue, somehow the `getFieldName` in Field.js is getting `parentField.0` as the context.parentFieldName (that seems right), and `0.childField` for this.props.fieldName (that seems wrong). Any ideas on how to go about fixing this? The only thing I changed for RN compatibility is this (in ArrayContextItem.js):
````javascript
isRN () {
  return navigator.product === 'ReactNative'
}

render () {
    if (this.isRN()) {
      const {View} = require('react-native');
      return (
        <View>
          {this.props.children}
        </View>
      )
    }
    return (
      <div>
        {this.props.children}
      </div>
    )
  }
````

### PR DESCRIPTION
**Pull request by JulianKingman**
ArrayField had a div, so this uses a view instead if the platform is react native.

This also fixes #64.

Also, for some reason "main" in package.json is listed as `./lib`, a folder that doesn't exist, I changed it to `./src`. Make sense?

### CODE REVIEW

File: src/Array/index.js [hunk 1]
```diff
@@ -100,11 +100,12 @@ export default class ArrayComponent extends React.Component {
     if (this.props.renderItem) return this.props.renderItem(item, index)
     if (this.props.children) return this.props.children
     if (!this.props.schema) throw new Error(`You must pass children to the array field "${this.props.fieldName}"`)
-    const schemaFieldName = replaceIndexKeys(this.props.fieldName)
-    let keys = this.props.schema.objectKeys(`${schemaFieldName}.$`)
+    let schemaFieldName = replaceIndexKeys(this.props.fieldName)
+    const keys = this.props.schema.objectKeys(`${schemaFieldName}.$`)
+    console.log('keys', keys);
```
Comment (fermuch) [inline src/Array/index.js]: You forgot to remove this log :stuck_out_tongue:

Comment (JulianKingman) [inline src/Array/index.js]: Thanks, removed.
